#!/usr/bin/env python3
"""Build kb/fxdub.db — the fx-dub project knowledge database.

Idempotent: drops and recreates every table from the seed data below, which is
the single source of truth (edit THIS file, rerun, commit both). Every row
carries a class:
  A = measured/verified on-account (billing feed, API pull, decoded bytes, get_node)
  B = agent-reported or otherwise second-hand; advisory until measured
Dates are verification dates; the 30-day freshness rule applies (stale = advisory).

Run:  python kb/build_db.py        (from repo root; writes kb/fxdub.db)
Query examples: see kb/README.md
"""
import sqlite3, os, datetime

DB = os.path.join(os.path.dirname(__file__), "fxdub.db")

NODES = [
    # (name, pack, status, cls, notes)
    # status: present = verified in live catalog (get_node / pulled graph); reported = agent-reported; absent = verified/reported absent
    ("UNETLoader", "core", "present", "A", "COMBO carries acestep_v1.5_xl_base_bf16 + xl_sft + xl_turbo + 1.5_turbo + 1.5_base. Split-file diffusion models live HERE, never in CheckpointLoaderSimple."),
    ("VAELoader", "core", "present", "A", "COMBO carries ace_1.5_vae.safetensors."),
    ("CLIPLoader", "core", "present", "A", "COMBO carries qwen_0.6b/1.7b/4b_ace15; type COMBO includes 'ace'."),
    ("DualCLIPLoader", "core", "present", "A", "Used by the measured Motif reference stack to load both qwen ace15 encoders."),
    ("CheckpointLoaderSimple", "core", "present", "A", "Carries ace_step_1.5_turbo_aio.safetensors (AIO: MODEL+CLIP+VAE). Its list is NOT the catalog."),
    ("TextEncodeAceStepAudio1.5", "core", "present", "A", "tags/lyrics/seed/bpm/duration/timesignature(2,3,4,6 STRING)/language/keyscale(34 COMBO)/codes-LM knobs. Grammar: 'Genre:' concrete musical prose (measured, prompt lab)."),
    ("EmptyAceStep1.5LatentAudio", "core", "present", "A", "The 1.5 latent node (seconds 1-1000). v2 wrongly used the 1.0 node with the 1.5 stack."),
    ("EmptyAceStepLatentAudio", "core", "present", "A", "The 1.0 latent node ('Empty Ace Step 1.0 Latent Audio')."),
    ("ModelSamplingAuraFlow", "core", "present", "A", "shift 3 in the measured ACE recipe."),
    ("ConditioningZeroOut", "core", "present", "A", "The reference stack's negative-conditioning source."),
    ("KSampler", "core", "present", "A", "XL-base measured recipe: euler/simple/50 steps/cfg 6."),
    ("VAEDecodeAudio", "core", "present", "A", "ACE 1.0 decodes 44.1 kHz stereo (measured); ACE 1.5 mix decodes 48 kHz (KB wave 7)."),
    ("Florence2Run", "comfyui-florence2", "present", "A", "Pin do_sample=false + fixed seed for reproducibility. Cloud cost ~6.73 gpu-sec/caption (wave 8)."),
    ("DownloadAndLoadFlorence2Model", "comfyui-florence2", "present", "A", "microsoft/Florence-2-large fp16/sdpa is the measured captioner config."),
    ("FL_ChatterboxTTS", "FL pack", "present", "A", "audio_prompt OPTIONAL -> default voice runs headlessly. Output 24 kHz MONO (measured). Perth watermark embedded."),
    ("FL_ChatterboxDialogTTS", "FL pack", "reported", "B", "Multi-speaker A-D; REQUIRES speaker reference AUDIO -> local-only (no cloud audio upload)."),
    ("VHS_LoadVideo", "videohelpersuite", "present", "A", "skip_first_frames/frame_load_cap act on the ONE output stream — capping here starves the mux (trap 8)."),
    ("VHS_VideoInfo", "videohelpersuite", "present", "A", "Unpacks video_info -> source/loaded fps, frame_count, duration, w/h (10 outputs)."),
    ("VHS_VideoCombine", "videohelpersuite", "present", "A", "AUDIO input optional; formats gif/webp/h264-mp4/h265-mp4/ffmpeg-gif/webm; frame_rate FLOAT-wirable; trim_to_audio bool."),
    ("VHS_SelectEveryNthImage", "videohelpersuite", "present", "A", "images->IMAGE+count; select_every_nth + skip_first_images. The Florence-branch subsampler (F3 fix)."),
    ("AudioStandardize", "AudioTools", "present", "A", "Channel layout ONLY (mono/stereo). NOT a sample-rate converter."),
    ("AudioMix", "AudioTools", "present", "A", "Sum of two streams + per-input gain_db. Rate reconciliation policy undocumented — measure output header. MEASURED 2026-08-23: gain_1_db/gain_2_db are clamped -24..+6 dB; +7 returns value_bigger_than_max, so a larger boost needs AudioAdjustVolume ahead of the bus."),
    ("AudioCombine", "AudioTools", "present", "A", "method add/mean/subtract/multiply/divide; NO gain input; add is clip-prone."),
    ("AudioLoudnessMeter", "AudioTools", "present", "A", "loudness_info STRING ('Integrated Loudness: X LUFS') — needs SaveText to reach outputs."),
    ("SaveAudioAdvanced", "core", "present", "A", "The blessed master saver (FLAC/WAV). Plain SaveAudio is deprecated."),
    ("SaveText", "core", "present", "A", "Required for any STRING that must reach the output manifest."),
    ("AudioAmplify", "AudioTools", "reported", "B", "gain_db, per-stem staging."),
    ("AudioPad", "AudioTools", "broken", "A", "pad_start/end_seconds — meant to be the timed-placement primitive, but every call on Comfy Cloud raises UnboundLocalError: pad_samples. Use EmptyAudio + AudioConcat."),
    ("AudioTrim", "AudioTools", "reported", "B", None),
    ("AudioConcat", "AudioTools", "reported", "B", "direction after/before; NO crossfade parameter."),
    ("AudioDelay", "AudioTools", "reported", "B", "Echo effect (delay_ms/feedback/mix), not a timeline shift."),
    ("AudioNormalize", "AudioTools", "reported", "B", None),
    ("AudioBPMDetector", "AudioTools", "reported", "B", "Tempo only — not onsets."),
    ("AudioReactiveParam", "AudioTools", "reported", "B", "AUDIO->FLOAT amplitude envelope; not onset segmentation."),
    ("FB_Qwen3TTSVoiceDesign", "Qwen3-TTS", "reported", "B", "Designed voice via instruct text; cloud-safe no-audio-input VO alternative. Output rate UNMEASURED."),
    ("FB_Qwen3TTSDialogueInference", "Qwen3-TTS", "reported", "B", "Multi-speaker."),
    ("sample-rate-conversion node", "-", "absent", "B", "NO explicit SRC node on the allowlist (agent-verified search). 48 kHz is not an exposed knob in-graph."),
    ("shot-boundary / onset detector", "-", "absent", "B", "None on allowlist. Spot-effect timing must come host-side."),
    ("audio pan node", "-", "absent", "B", "None found."),
    ("float math / clamp node", "-", "unknown", "B", "Asked in round 4 (F5). If absent, bed duration stays a manual knob."),
    # --- measured by session 5's re-mux round (2026-08-23) ---
    ('SyncLipSyncNode', 'core (partner/video/sync.so)', 'present', 'A', 'Nine required inputs; five are conditional model.* sub-fields under a COMFY_DYNAMICCOMBO_V3 whose only option is sync-3. All five accepted at runtime exactly as advertised. speaker_selection defaults to "default" - pin it to "coordinates". sync_mode "silence" is the only mode that leaves the picture length alone. Non-deterministic regardless of seed. ~40 credits/second of OUTPUT.'),
    ('AudioVideoCombine', 'audio-separation-nodes-comfyui', 'broken', 'A', 'ImportError: TorchCodec is required for save_with_torchcodec. Use VHS_VideoCombine.'),
    ('AudioAdjustVolume', 'core', 'present', 'A', "Volume in dB as an INT. The escape hatch for gains outside AudioMix's -24..+6 dB clamp; the delivered mix's VO +7 dB goes here."),
    ('GetVideoComponents', 'core', 'present', 'A', 'Outputs IMAGE, AUDIO, FLOAT fps, INT bit depth. Decodes at the SOURCE cadence: a 473-frame/47fps container returns 161 frames. That is what makes the mux round-trip restore the original frame count.'),
    ('ImageFromBatch', 'core', 'present', 'A', 'CLAMPS an out-of-range batch_index to the last frame instead of erroring. Cross-check returned images by content hash before trusting you got the frame you asked for.'),
    ('SaveVideo', 'core', 'present', 'A', 'format auto|mp4, codec auto|h264. Do NOT send codec.encoding: its options are objects, not strings, and pre-flight raises candidate.toLowerCase is not a function with no verdict.'),
]

MODELS = [
    # (file/name, loader, license, commercial, cls, notes)
    ("acestep_v1.5_xl_base_bf16.safetensors", "UNETLoader", "MIT (code+weights)", "yes", "A", "The measured production bed/music model. Recipe: euler/simple/50/cfg6 + AuraFlow shift 3; 48 kHz decode; 60 s production window."),
    ("ace_1.5_vae.safetensors", "VAELoader", "MIT", "yes", "A", None),
    ("qwen_0.6b_ace15.safetensors", "CLIPLoader/DualCLIPLoader type=ace", "MIT", "yes", "A", None),
    ("qwen_4b_ace15.safetensors", "CLIPLoader/DualCLIPLoader type=ace", "MIT", "yes", "A", None),
    ("ace_step_1.5_turbo_aio.safetensors", "CheckpointLoaderSimple", "MIT", "yes", "A", "AIO MODEL+CLIP+VAE. Turbo — sampler must mirror the official turbo template (~8 steps/cfg 1), NOT the XL recipe. Unaudited."),
    ("ace_step_v1_3.5b.safetensors", "CheckpointLoaderSimple", "Apache-2.0", "yes", "A", "ACE 1.0 line (the v1 as-built). Decodes 44.1 kHz. Superseded by 1.5 on quality AND license."),
    ("microsoft/Florence-2-large", "DownloadAndLoadFlorence2Model", "MIT", "yes", "A", "In-Comfy the wrapper manages loading. Native transformers outside Comfy needs florence-community/* conversions."),
    ("Chatterbox (Resemble AI)", "FL_Chatterbox*", "MIT + Perth watermark", "yes", "A", "Cloning consent-gated + local-only (no cloud audio upload). First cloud e2e measured 2026-08-21."),
    ("stable_audio_3_medium.safetensors", "CheckpointLoaderSimple + CLIPLoader t5gemma type=stable_audio", "Stability Community License (<$1M) + Gemma ToU rider", "conditional", "A", "SFX lane. lcm/8/cfg1, 44.1 kHz, ~2.6 cr/10 s. NOT 'permissive' — agent's round-1 claim corrected."),
    ("Qwen3-TTS", "FB_Qwen3TTS*", "Apache-2.0", "yes", "B", "Cloud VO alternative (preset/designed voices). Run one line before relying."),
    ("MMAudio", "local only", "code MIT / weights CC-BY-NC 4.0", "no", "A", "Direct V2A — best sync, commercially blocked. KB wave-verified."),
    ("VHS/AudioTools/Florence2 wrapper packs", "-", "MIT-class wrappers", "yes", "B", "Wrapper license != model weights license. Decisive axis is the weights."),
]

RUNS = [
    # (job_id, date, description, gpu_sec, credits, rate, ch, bits, dur, sha256, cls, source)
    ('3183b05a-3e99-4cf4-b0bf-b49111d263d7', '2026-08-22', "Two-voice dialogue via Qwen3 clone+RoleBank+DialogueInference - PROVED voice cloning works on cloud (LoadAudio storage key -> VoiceClonePrompt). 17.380 s against a 10.06 s clip: my instruct said 'speaks slowly and unhurried' and the model obliged", 0.0, 0.0, 24000, 1, 16, 17.38, None, 'A', 'FLAC STREAMINFO decode'),
    ('9e027e2f-fd4c-4dcd-80ca-66d3aae22cb0', '2026-08-22', 'Same, brisk instruct + tight pauses: 11.494 s. Still 1.43 s over', 0.0, 0.0, 24000, 1, 16, 11.494, None, 'A', 'FLAC STREAMINFO decode'),
    ('e21df5d1-3493-46de-b3c0-f39af504c00c', '2026-08-22', "x_vector_only=true clone: 15.361 s - WORSE. The speaker embedding drops the reference's prosody so the model picks its own slower pacing; the FULL clone carries the tighter delivery. Counterintuitive, recorded", 0.0, 0.0, 24000, 1, 16, 15.361, None, 'A', 'FLAC STREAMINFO decode'),
    ('25fb23a9-ae8a-44bb-9db7-846fa9bec883', '2026-08-22', "AudioSpeedShift fit test: 1.08x -> 10.645 s, 1.15x -> 9.984 s (fits). Sample RATE unchanged while sample COUNT dropped, so it is a genuine time-compression not a resample. REJECTED as a cheap technique by the Director - the premium engine's native speed control is the right lever", 0.0, 0.0, 24000, 1, 16, 9.984, None, 'A', 'FLAC STREAMINFO decode'),
    ('85413a15-1fef-4733-8f2e-4335cd1bbcd2', '2026-08-22', 'ElevenLabs eleven_v3 voice bake-off (PAID). Pairing A Callum+Bill 10.320 s; pairing B Roger+Brian 8.880 s - FITS the 10.06 s clip with no stretching. ALL 48 kHz, which also removes the rate mismatch at source', 0.0, 0.0, 48000, 2, 16, 8.88, None, 'A', 'FLAC STREAMINFO decode'),
    ('11759129-1d01-4d36-9de4-7e055afbd1f4', '2026-08-22', 'fx-dub v2.7 FINAL - ElevenLabs VO (Roger+Brian) + ElevenLabs SFX bed, VO -3 dB / bed -12 dB. RECEIPT 19/19: mix -18.18 LUFS, dialogue 10.86 LU above bed, 48 kHz throughout, 161 frames intact. MECHANICALLY COMPLETE; Director rejected the VOICES as unnatural and not deep enough', 0.0, 0.0, 48000, 2, 16, 10.0, None, 'A', 'audition_receipt.py 19/19 + FLAC/MP4 decode'),
    ('35bef893-43ef-4153-bbc2-e95cd590ecf9', '2026-08-22', 'fx-dub v2.3 - full rebuild: ElevenLabs SFX bed (rain + corrected wet-concrete footsteps) replacing ACE-Step, Qwen3 VoiceDesign gritty VO, bed on AudioMix.audio_1, ImageFromBatch(80) caption fix. Mix 48 kHz (was 24), bed -17.20 LUFS (was -39.29), dub 161 frames at 10.062 s', 0.0, 0.0, 48000, 2, 16, 10.0, None, 'A', 'FLAC STREAMINFO + MP4 atom decode'),
    ('b88aa66d-c3c8-49c1-95e9-03cbdbb24f82', '2026-08-22', 'LoadAudio storage-key probe + first gain-staged remix - PROVED LoadAudio resolves a key absent from its COMBO (reloaded bed metered -17.20, exact round-trip). VO +6 dB -> -17.94 LUFS, bed -13 dB, separation 12.26 LU, mix -22.05', 0.0, 0.0, 48000, 2, 16, 10.0, None, 'A', 'FLAC STREAMINFO decode'),
    ('0483fa75-3f42-420c-82f2-65326dcdc16b', '2026-08-22', 'fx-dub v2.3 FINAL - rebuilt entirely from LoadAudio storage keys (no regeneration). VO +10 dB -> -13.94 LUFS, bed -9 dB -> -26.20, separation 12.26 LU, MIX -18.05 LUFS against the -18.0 target. RECEIPT 19/19 after correcting the two defective checks', 0.0, 0.0, 48000, 2, 16, 10.0, None, 'A', 'audition_receipt.py 19/19 + FLAC/MP4 decode'),
    ('678474ca-0bb8-4201-9236-8f65dd5789a8', '2026-08-22', 'fx-dub v2.2 AUDITION - FIRST SUCCESSFUL fx-dub RUN EVER; 7/7 artifacts, receipt 14/18, dubbed.mp4 carries audio (vide+soun+mdir) with 161 frames intact at 10.069 s; ran with input_overrides select_every_nth=161 to dodge the Florence caption-list bug', 17.281021, 4.6, 24000, 2, 16, 10.0, None, 'A', 'billing feed + FLAC STREAMINFO + MP4 atom decode + audition_receipt.py'),
    ('86d366c7-2d31-4bef-a98e-e71c3e2764d3', '2026-08-22', 'fx-dub v2.2 audition attempt 1 FAILED - TypeError write() argument must be str not list at SaveText 2948872656512997 (Florence returned 6 captions for 6 subsampled frames); no outputs persisted', 0.0, 0.0, None, None, None, None, None, 'A', 'job error payload'),
    ('520c4ec7-d521-4823-8ccb-61dd1ae63e27', '2026-08-22', 'fx-dub v2.1-turbo audition attempt 1 FAILED - identical caption-list failure at SaveText 3707348903304622; confirms the defect is systemic', 0.0, 0.0, None, None, None, None, None, 'A', 'job error payload'),
    ('d9e22892-d17e-4594-9768-c57135426019', '2026-08-22', 'mix-bus rate + bed-loudness probe (hand-authored API graph) - SETTLED: AudioMix adopts audio_1 rate (bed-first 48 kHz vs VO-first 24 kHz); AudioMerge also 48 kHz; bed after -15 dB = -39.29 LUFS, explaining the gated +0.00 LU dialogue-anchored failure', 12.791002, 3.4, 48000, 2, 16, 10.0, None, 'A', 'billing feed + FLAC STREAMINFO decode'),
    ('d8ab8968-fa35-4979-b063-4a9df7121862', '2026-08-22', "SFX bake-off, ElevenLabs eleven_sfx_v2 (PAID partner API) - 5 candidates ALL 48 kHz stereo at EXACTLY 10.000 s; layered rain+footsteps(-4 dB) measures -17.44 LUFS; the fix for the Director verdict 'I did not hear any sfx'", 0.0, 0.0, 48000, 2, 16, 10.0, None, 'A', 'FLAC STREAMINFO decode'),
    ('6e52b225-b47c-4cd4-b351-5b1fdbc5e972', '2026-08-22', 'Voice bake-off - Qwen3-TTS VoiceDesign from a written character brief (4.617 s), Uncle_fu preset (2.937 s), Eric+instruct (4.457 s), Chatterbox exaggeration 1.4 cfg 0.3 (3.240 s); ALL 24 kHz MONO', 0.0, 0.0, 24000, 1, 16, None, None, 'A', 'FLAC STREAMINFO decode'),
    ("26a78ccd-06c3-4618-8822-08a547c7e8e9", "2026-08-19", "Florence-2-large caption, 1 image (caption-florence2-v1)", 6.73, 1.8, None, None, None, None, None, "A", "readouts wave 8, billing feed"),
    ("d3cda2f7-bc64-413e-ae14-dc0d279e5dff", "2026-08-21", "ACE-Step 1.0 SFX demo, 10 s ask, 50 steps (rain ambience)", 7.628, 2.0, 44100, 2, 16, 9.938, "676bbbcbc171261c20198a08044ef992de626f18b472434232680f86f7cc25aa", "A", "billing feed + FLAC STREAMINFO decode"),
    ("19c22524-a7b0-48ee-bb99-37e1651e8067", "2026-08-21", "FL_ChatterboxTTS demo line, default voice — FIRST e2e cloud measurement", 6.545, 1.7, 24000, 1, 16, 5.800, "7cf405e338dc8921a560fcdab917e714456056a61c7689f8ac0ed20c2a1fe44b", "A", "billing feed + FLAC STREAMINFO decode"),
    ("b81c6dbf-confirmation", "2026-08-18", "ACE 1.5 XL 120 s track + Demucs 4-stem (Motif builds v2 confirmation)", 29.7, 7.9, 48000, 2, 16, 120.0, None, "A", "readouts wave 7 (full UUID in wave receipts)"),
    ("7b966963-confirmation", "2026-08-18", "SA3 Medium SFX 3 s (partial cache); uncached 10 s ~= 9.8 gpu-sec", 1.1, 0.3, 44100, 2, 16, 2.972, None, "A", "readouts wave 7"),
    ("c4d0c2a8-c308-439a-a704-68423cb41c8e", "2026-08-21", "Wan t2v test clip, 5 s attempt (superseded by the 10 s take)", 172.961, 46.0, None, None, None, None, None, "A", "billing feed"),
    ("1c4e02a8-0a7f-4806-b548-201160f42530", "2026-08-21", "Wan t2v AUDITION CLIP: 10 s photorealistic rain/cyborg, silent — 161 frames @ 16 fps, h264, no audio track", 511.712, 136.0, None, None, None, 10.062, "9985a8ba6197ea7c02adc99c4c3aafc2a9d1cfa13e535ede64908ebea327a30c", "A", "billing feed + local MP4 atom probe"),
    # --- measured by session 5's lip-sync run (rounds 16-17) ---
    ('aba137d3-fb5e-4365-94fc-cf23cab04640', '2026-08-23', 'Frame extract, decode-only (LoadVideo by storage key -> GetVideoComponents -> 3x ImageFromBatch -> SaveImage at 20/60/120). PROVED LoadVideo resolves a cloud storage key with NO upload. Frames confirmed 832x480. Revealed the Florence caption hallucination: ONE man on screen, not two.', 0.0, 0.0, None, None, None, None, None, 'A', 'PNG probe + Director confirmation'),
    ('12b8cab4-c91f-4693-8569-e3b87b7ba47c', '2026-08-23', 'sync.so PROBE, sync_mode=cut_off (PAID, ~58 credits at 40 cr/s x 1.4375s). Proved all five dotted model.* slots accepted at runtime, LoadAudio resolves storage keys, coordinate targeting drives the mouth, and cut_off = shorter track exactly per tooltip. Output 68 frames / 1.4375s = ~47 fps from a 16 fps source -> first evidence of re-timing. Caught that d7ba748c is 1.415s with NO leading silence.', 0.0, 58.0, 48000, 2, None, 1.4375, '517d03a27b767a4137df776a8b9fa473066c6af4cf1204dd20a4d0cb49cfb9f5', 'A', 'MP4 atom probe'),
    ('950bd9c4-94a2-46f7-941d-5d064842c764', '2026-08-23', 'MAC positioned stem, FREE: EmptyAudio(2.279s) + AudioConcat(d7ba748c). Measured 3.694s = 2.279 + 1.415, confirming the cloud take is 1.415s of content with no leading silence.', 0.0, 0.0, 48000, 2, None, 3.694, 'd91875230a22d7325bf0e0403f3d92ee1596954c28c936669648c55c9c9c5367', 'A', 'FLAC STREAMINFO decode'),
    ('f8bbdb6b-58ee-47d0-affd-8395eb9fe2f4', '2026-08-23', 'MAC FULL-LENGTH positioned stem, FREE: + EmptyAudio(6.3685s) tail. Measured 483000 samples / 48 kHz = 10.0625s EXACTLY, delta 0.0000s vs the picture - eliminating the silence-pad-direction unknown without a paid test.', 0.0, 0.0, 48000, 2, None, 10.0625, '4afc41d2a2df7f4ed8d6db2f52bc767365dfc5467a3bee9c7d03ed18324e0541', 'A', 'FLAC STREAMINFO decode'),
    ('4b2339b4-804a-42aa-8198-e2bf89877803', '2026-08-23', 'sync.so FULL PASS (PAID, ~403 credits at 40 cr/s x 10.0625s). sync-3, silence, coordinates (348,122), speaker_frame 60, seed 42. Output 832x480 / 10.0625s video / 10.0838s audio / 473 frames (~47 fps). Duration and resolution preserved; frame count NOT. Verified visually: mouth articulating at 2.5s inside MAC line, mouth CLOSED at 7.5s while VOICE speaks off-frame.', 0.0, 403.0, 48000, 2, None, 10.0625, '4ff033530f2ae565620466f55692d6cb34ad42f0f6b517302c239c49b5993627', 'A', 'MP4 atom probe + frame inspection'),
    # --- measured by session 5's re-mux round (2026-08-23) ---
    ('632c1ebd-046c-4b26-9d5c-c69334fbd87d', '2026-08-23', "Duration probe on the MAC raw take 37d38cda (FREE, LoadAudio -> SaveAudioAdvanced). Measured 3.624s, matching local A_bytedance_grit_p0.flac. With d7ba748c at 1.415s, NEITHER named key matches the delivered mix's 1.68s MAC line.", 0.0, 0.0, 48000, 2, None, 3.624, None, 'A', 'FLAC STREAMINFO decode'),
    ('b8590ec8-cf82-45c3-9402-76358827b2c7', '2026-08-23', 'FAILED (free): AudioMix gain_2_db=7.0 rejected, value_bigger_than_max, max 6.0. Proved the recorded mix recipe is not reproducible through AudioMix alone.', 0.0, 0.0, None, None, None, None, None, 'A', 'platform validation error'),
    ('94097e2f-3468-4ecd-87d5-c613e636482c', '2026-08-23', 'Mix rebuilt from stem storage keys (FREE): AudioAdjustVolume(VO,+7) -> AudioMix(audio_1=bed, gain_1_db=-12). BYTE-IDENTICAL to the delivered v28 mix by FLAC STREAMINFO md5 c34976a8594c3705cc3622eef75033f6.', 0.0, 0.0, 48000, 2, 16, 10.0, 'e60f56de890dd9dddd987f1f002e98a51f405248056d681d06f717ba1ebe11bc', 'A', 'FLAC STREAMINFO md5 equality'),
    ('3397f3e9-f7bd-44f1-8b37-6b585fa5599a', '2026-08-23', 'FAILED (free): AudioVideoCombine raised ImportError, TorchCodec required for save_with_torchcodec. Node is broken on cloud; recorded in graph_lint.BROKEN_ON_CLOUD.', 0.0, 0.0, None, None, None, None, None, 'A', 'execution.node ImportError'),
    ('096ce861-32bb-4bf0-bca6-5dc25c790ed2', '2026-08-23', 'THE DELIVERABLE (FREE): lip-synced picture + the shipped mix, via GetVideoComponents -> VHS_VideoCombine with frame_rate LINK-driven. Measured 832x480, 161 frames, video 10.0625s, audio 10.0693s, both tracks present - the original contract intact, with the sync re-timing undone by the round-trip.', 0.0, 0.0, 48000, 2, None, 10.0625, 'a76041bc49edad645d0ccdbf8997873a01508e35b715c5babf76c51cadae1531', 'A', 'MP4 atom probe'),
]

GRAPHS = [
    # (name, location, workflow_id, nodes, status, cls, notes)
    ("Describe a video (Florence2) [v1]", "workflows/comfy-cloud/as-built/describe-a-video-florence2.json + cloud file", None, 13, "archived; superseded", "A", "Agent's v1 full chain. 10-item defect ledger in as-built README."),
    ("Demo: SFX (ACE-Step)", "workflows/comfy-cloud/as-built/demo-sfx-ace-step.json + cloud record", "0a8b29f6-c16c-4cd4-91ce-69d12bba1cc8", 7, "archived; ran 1x", "A", None),
    ("Demo: Dialogue (ChatterBox)", "workflows/comfy-cloud/as-built/demo-dialogue-chatterbox.json + cloud record", "843f8a61-e3a4-412e-b349-333fa827f290", 2, "archived; ran 1x", "A", None),
    ("fx-dub v2", "workflows/comfy-cloud/as-built/fx-dub-v2.json (editor) + .api.json + RESTORED cloud record", "65a063a5-9342-4297-8cfa-01313178fab9", 29, "archived + restored server-side; superseded by v2.1 order", "A", "Defects F1-F5. The original file 'fx-dub v2.json' was CLOBBERED by the agent's open_workflow (now holds a 19-node Motif dup) — restored copy lives at the workflow_id here."),
    ("Motif builds v2 (reference)", "readouts model-knowledge/workflows/audio/ace15-track-to-stems.json + cloud record", "78a76ecd-7ae2-452a-afea-ad55a8d290f8", 19, "measured reference — DO NOT MODIFY", "A", "The receipt-verified ACE 1.5 XL stack: UNETLoader+VAELoader+DualCLIPLoader(ace), ConditioningZeroOut negative, EmptyAceStep1.5LatentAudio."),
    ("fx-dub v2.1", "workflows/comfy-cloud/as-built/fx-dub-v2.1.json + cloud file 'fx-dub v2.1.json'", None, 34, "SUPERSEDED by v2.2 (its VHS loader cannot reach the asset namespace); wire-verified clean; never run", "A", "XL split stack (UNET+VAE+DualCLIP type=ace), ConditioningZeroOut negative, EmptyAceStep1.5LatentAudio, VHS_SelectEveryNthImage(30) on the Florence branch only, mux reads full loader stream. Open drift: Florence task = detailed_caption (spec said more_detailed_caption); duration knob manual (no float-math node on the allowlist)."),
    ("Ref: fx-dub v2 (mirror source)", "cloud throwaway tab", None, 29, "throwaway; safe to delete", "A", "The agent's read-only mirror tab — its open_workflow went here, not onto a live tab (standing rule honored)."),
    ("fx-dub v2.2", "cloud file 'fx-dub v2.2.json' (29,884 B)", None, 34, "BUILT + wire-verified clean; loader CLEARED; never run; THE AUDITION GRAPH", "A", "The ingest fix: LoadVideo(ea68c5aa....mp4) -> GetVideoComponents -> IMAGE to BOTH VHS_SelectEveryNthImage(30) and VHS_VideoCombine.images. VHS_VideoInfo + VHS_LoadVideo removed; GetVideoComponents fps/AUDIO outputs deliberately unconnected. PrimitiveFloat 16.0 -> VHS_VideoCombine.frame_rate VERIFIED on input slot 4 (link 718920623009028) — closes the round-6 deferred check. Florence drift FIXED (more_detailed_caption). All 7 prefixes under fxdub22/. Loader asset confirmed byte-identical to the local fixture via get_output + local probe. Open: Florence2Run.control_after_generate=randomize (should be fixed)."),
    ("fx-dub v2.1-turbo", "cloud file 'fx-dub v2.1-turbo.json' (29,545 B)", None, 34, "REBUILT + wire-verified clean; cleared to run; never run; the A/B partner to v2.2", "A", "Round-10 rebuild verified value-by-value against v2.2: EXACTLY THREE VALUES DIFFER — UNETLoader.unet_name=acestep_v1.5_xl_turbo_bf16.safetensors, KSampler.steps=8, KSampler.cfg=1, all three matching the official audio_ace_step1_5_xl_turbo template. CheckpointLoaderSimple removed, split stack restored, 34 nodes. Everything else identical incl. AuraFlow shift 3, euler/simple/denoise 1, encoder cfg_scale 2, the shared seed, the mix bus, the same LoadVideo clip, and the 16.0 frame_rate pin on slot 4. All 7 prefixes under fxdubturbo/. NAME LAGS LINEAGE: built on v2.2's ingest, not v2.1's; the agent has no rename tool."),
]

THREADS = [
    # (round, direction, files, state, summary)
    (1, "inbound", "readouts dialogs 2026-08-21-fxdub-01-{transcript,verification}.md", "closed", "Director-run dialog: v1 build + 2 demos. Graphs pulled, demos verified from billing + headers."),
    (2, "outbound+reply", "…-02-{brief,reply,verification}.md", "closed", "v2 build order -> agent delivered 29-node v2; loader claim REFUTED Class A; 3 blockers found."),
    (3, "outbound+reply", "…-03-brief.md + 03-reply (clobber incident)", "closed", "v2.1 fix order -> agent clobbered the v2 tab via open_workflow mid-execution; stopped and asked before proceeding."),
    (4, "outbound+reply", "…-04-{brief,reply,verification}.md", "closed", "GO for v2.1 -> agent built it (33 nodes, validate-only honored, open_workflow used only into a throwaway tab). Verified clean our side: F1-F6 all genuinely fixed."),
    (5, "outbound+reply", "…-05-brief.md + reply", "closed", "2 drift items + audition blockers raised. Agent fixed the Florence task, answered Q1 (no outputs->inputs path exists) and Q2 (ffprobe reads a clean 16/1 from the track; could not see the movie header; recommended pinning frame_rate) — honest about what it could not verify."),
    (6, "outbound+reply", "…-06-brief.md + reply", "closed", "Pin ordered and DONE: agent wired PrimitiveFloat 16.0 -> frame_rate (verified our side: 34 nodes, node 421351014920351 = 16.0), kept VHS_VideoInfo in-graph, recorded the fixture-specific caveat, ran nothing, left the loader untouched."),
    (7, "outbound+reply", "…-07-brief.md + reply", "closed", "Disambiguation: a relayed job-id + output URL were mistaken for an instruction; agent correctly refused to infer one and asked. Confirmed our side the upload had NOT landed (VHS_LoadVideo video COMBO = ['bedroom.mp4']). Agent acknowledged and held: loader untouched, no run, no re-validate."),
    (8, "outbound+reply", "…-08-{brief,reply}.md", "closed", "Director green-lit the turbo tab. Ordered `fx-dub v2.1-turbo` as a CONTROLLED A/B: exact copy of v2.1 with only the generator block swapped (CheckpointLoaderSimple ace_step_1.5_turbo_aio + the OFFICIAL turbo template's sampler settings, read not guessed) and filename_prefix -> fxdubturbo/* so artifacts never collide. Everything else held constant. Validate-only; both tabs audition together on the same clip."),
    (9, "outbound+reply", "…-09-{brief,reply,verification}.md", "closed", "Agent's loader-set attempt was REJECTED by the platform and it reported the rejection honestly. Root cause found our side: TWO video namespaces (VHS input folder = ['bedroom.mp4'] vs core LoadVideo asset namespace = 9 mp4s holding the attachment). Ordered `fx-dub v2.2`: core LoadVideo -> GetVideoComponents -> the existing IMAGE consumers, VHS_VideoInfo removed, 16.0 pin retained, fxdub22/* prefixes. Agent must IDENTIFY the right asset by probe (161 frames / 16 fps / 10.0625 s / no audio) and stop if none match. REPLY: agent built v2.2 (34 nodes, ready_to_run, 0 errors) and identified the asset CORRECTLY, declaring an honest gap (per-stream frames/fps were truncated before it could read them). WE THEN CALLED ITS LOADER VALUE A HARD BLOCKER AND WERE WRONG — see traps. get_output + a local probe confirmed the asset byte-identical to the fixture and closed the agent's gap for it."),
    (10, "outbound+reply", "…-10-{brief,reply,verification}.md", "closed", "Correction round. (1) Told the agent on the record that its asset ID was right and ours was the error, and closed its declared gap with our own measurement (161 frames / 10.0625 s / no audio / 16.000 fps / byte-identical). (2) Gave the REAL turbo recipe read from the official template audio_ace_step1_5_xl_turbo — restore the SPLIT stack, change only unet_name -> acestep_v1.5_xl_turbo_bf16, steps -> 8, cfg -> 1 — and told it round 8's CheckpointLoaderSimple instruction was our mistake and that its relay was truncated on our side. (3) Rename the turbo tab to fx-dub v2.2-turbo (it was copied from v2.2). (4) Set Florence2Run.control_after_generate to fixed in both tabs. (5) Asked whether FL_ChatterboxTTS treats seed 0 as a literal or a randomize sentinel, with an explicit 'cannot determine' allowed. REPLY: turbo tab rebuilt correctly — verified value-by-value, EXACTLY the three-value delta, 34 nodes, split stack restored. Agent answered 'cannot determine' on the Chatterbox seed as invited, and correctly reported that Florence2Run has NO control_after_generate schema input, so OUR round-10 instruction was the unactionable one — item dropped. No rename tool, so the turbo tab's name still lags its lineage. Both graphs cleared to run."),
]

TRAPS = [
    ("A checkpoint loader's COMBO is not the catalog — split-file diffusion models live under UNETLoader/VAELoader/CLIPLoader. Searching CheckpointLoaderSimple alone produced a false 'files not installed' claim.", "high", "A"),
    ("The in-app agent's open_workflow REPLACES the focused tab's canvas AND its saved file — destructive. Standing rule: open references in a NEW tab, or read them over the API instead.", "high", "A"),
    ("Wiring the SAME conditioning output to KSampler positive AND negative cancels CFG algebraically (neg + cfg*(pos-neg) = pos). Use ConditioningZeroOut (the reference stack's negative).", "high", "A"),
    ("VHS_LoadVideo's frame knobs (skip_first_frames/frame_load_cap) act on its ONE image stream — a cap for the captioner also starves VHS_VideoCombine. Subsample the Florence branch only (VHS_SelectEveryNthImage).", "high", "A"),
    ("frame_load_cap=0 + select_every_nth=1 sends EVERY frame to Florence-2 — a 60 s clip is ~1,700 captioned frames of GPU time.", "medium", "A"),
    ("ACE 1.0 decodes 44.1 kHz stereo; cloud Chatterbox decodes 24 kHz MONO; ACE 1.5 mix decodes 48 kHz. Never combine without conforming channels (AudioStandardize) — and there is NO SRC node, so measure the mix output rate from the FLAC header.", "high", "A"),
    ("SaveAudio (FLAC) is deprecated — masters go through SaveAudioAdvanced. MP3 padding breaks alignment.", "medium", "A"),
    ("STRING outputs (caption, loudness_info) reach the output manifest ONLY through SaveText — dangling STRINGs are lost headlessly.", "medium", "A"),
    ("Florence2Run do_sample=true breaks caption reproducibility and forfeits memo-cache pricing. Pin do_sample=false + fixed seed.", "medium", "A"),
    ("Editor-valid != API-valid: COMBO values are TYPE-strict at /api/prompt ('4' passes, 4 fails); UI-only nodes vanish headlessly. Graphs must be static-validation green.", "high", "A"),
    ("timesignature is a STRING COMBO ('2','3','4','6') — 2/4 is the silent default; keyscale is a 34-value major/minor enum (modes are rejections).", "medium", "A"),
    ("Cloud has NO audio-upload path: any node needing reference AUDIO (cloning, DialogTTS) is local-only.", "high", "A"),
    ("Pinned-seed byte-identity is memo-cache-only; a fresh re-execution reproduces the sound, not the bytes. Treat downloaded masters as canonical-by-hash.", "medium", "A"),
    ("The account-wide queue caps at 100 jobs — serialize batch submission (readouts trap ledger, measured on the library burn).", "medium", "A"),
    ("Turbo checkpoints need the turbo template's sampler (~8 steps/cfg 1) — running the XL recipe (50/cfg 6) on a turbo AIO overbakes at ~6x cost.", "medium", "B"),
    ("Video generation dwarfs the whole audio pipeline: one 10 s Wan t2v clip cost 511.7 gpu-sec (~136 cr) vs ~10 cr for a full fx-dub audio run. Never generate test footage casually — reuse the archived audition clip.", "high", "A"),
    ("The Wan-generated audition clip's mvhd movie timescale is 0 (malformed movie header; the per-track mdhd is correct at 16384/164864 = 10.062 s). VHS_VideoInfo.source_fps feeds VHS_VideoCombine.frame_rate — if fps derivation reads the movie header it may emit 0/NaN and produce a broken dub. VERIFY source_fps == 16.0 at the audition run before trusting the mux.", "high", "A"),
    ("An agent reporting 'this node has no X widget in its schema' can be wrong — the pulled graph JSON is the arbiter. v2.1's VHS_VideoCombine DOES carry pix_fmt/crf/save_metadata/trim_to_audio (verified in widgets_values), despite the agent reporting them absent.", "medium", "A"),
    ("Unrequested spec drift hides inside a correct-looking fix list: v2.1 silently changed the Florence task from more_detailed_caption to detailed_caption while reporting the Florence block 'carried over'. Diff widget values, not just topology.", "medium", "A"),
    ("There is NO video-into-inputs path over the API, in either toolset: the MCP's upload_file is image-only (.jpg/.jpeg/.png/.webp/.gif; an .mp4 is rejected validation.input) and the in-app agent has no route that writes to the inputs namespace. Video fixtures MUST be uploaded through the Comfy Cloud browser UI.", "high", "A"),
    ("Two probes reading DIFFERENT fields of the same file are not a contradiction: ffprobe reported a clean 16/1 from the TRACK while our atom probe found mvhd (MOVIE header) timescale 0. Both true. When a derived value could read either field, pin a primitive rather than betting on which one the node uses.", "medium", "A"),
    ("A bare id or URL pasted into an agent thread is NOT an instruction. A job id (billing/provenance) is not a workflow id and is not openable; a signed output URL cannot reach the inputs namespace. Label every reference as reference, and state the instruction in words.", "medium", "A"),
    ("`VHS_LoadVideo`'s `video` COMBO options ARE the live input-folder listing — read it with get_node to check whether an upload landed and to recover the exact filename, instead of relaying a filename by hand. (Measured 2026-08-21: options were exactly ['bedroom.mp4'], proving the audition upload had not happened.)", "medium", "A"),
    ("THERE ARE TWO VIDEO NAMESPACES AND THEY ARE NOT THE SAME. `VHS_LoadVideo.video` reads the VHS input folder (measured: only ['bedroom.mp4']); core `LoadVideo.file` reads the asset/attachment namespace (measured: 9 content-addressed .mp4s). An attachment can be present in one and invisible to the other — which is exactly what blocked the audition. Check BOTH before concluding a file is unreachable.", "high", "A"),
    ("`GetVideoComponents` (core, category video) converts VIDEO -> IMAGE + AUDIO + framerate FLOAT + bit-depth INT. It is the bridge from the asset-namespace `LoadVideo` to any IMAGE-consuming graph, and removes the dependency on the VHS input folder entirely — the better architecture for a published tool, since users' footage arrives via attachment.", "high", "A"),
    ("ABSENCE FROM A COMBO LISTING IS NOT PROOF OF INVALIDITY. get_node('LoadVideo').file enumerates the INPUT/attachment namespace; a cloud SaveVideo output lives in comfy-cloud-assets under a storage key that LoadVideo resolves but that COMBO never lists. We called a correct loader value a hard blocker on this basis and were WRONG. The authoritative job->asset mapping is get_output(prompt_id); the platform validator's ready_to_run is a stronger probe than our enumeration.", "high", "A"),
    ("The cloud storage key and the sha256 of the bytes are TWO DIFFERENT ADDRESSES FOR ONE FILE. Asset ea68c5aa....mp4 downloads to bytes whose sha256 is 9985a8ba... — byte-identical to our local fixture. Local hash matching against cloud asset names therefore always fails and proves nothing. Map job->asset with get_output, THEN download and hash.", "high", "A"),
    ("estimate_credits is a PRICING pass, not a validator. A minimal LoadVideo->GetVideoComponents->SaveImage graph prices identically (0 credits, no error) whether given a valid or an invalid COMBO value. Never use it to adjudicate graph validity.", "medium", "A"),
    ("A stale widget value sits UNDER every live link and wins the moment the link is cut. v2.2's VHS_VideoCombine.frame_rate widget still reads 8 beneath the PrimitiveFloat 16.0 link: cut that link and 161 frames silently render as a 20.1 s video against a 10 s bed, with no error. Same pattern (harmless while linked) on TextEncodeAceStepAudio1.5.duration=120, EmptyAceStep1.5LatentAudio.seconds=120, KSampler.seed=0, FL_ChatterboxTTS.text. Verify LINK PRESENCE, not widget value.", "high", "A"),
    ("The OFFICIAL ACE-Step 1.5 turbo template (audio_ace_step1_5_xl_turbo, 13 nodes) keeps the SPLIT stack: UNETLoader(acestep_v1.5_xl_turbo_bf16.safetensors) + VAELoader(ace_1.5_vae) + DualCLIPLoader(qwen_0.6b/qwen_4b, type=ace). It does NOT use CheckpointLoaderSimple or an AIO checkpoint. Sampler: steps 8, cfg 1, euler, simple, denoise 1; AuraFlow shift 3 unchanged; encoder cfg_scale 2 unchanged. base->turbo is a THREE-VALUE delta (unet_name, steps, cfg) — a genuinely controlled A/B. Our round-8 CheckpointLoaderSimple instruction was wrong.", "high", "A"),
    ("The editor graph and the node SCHEMA are different views, and a value visible in one may not be settable through the other. Florence2Run's widgets_values carries control_after_generate='randomize', but the node's inputs array has NO such entry — there is no API target to set. We ordered the agent to change it; it correctly refused to invent a target. Same shape as the LoadVideo COMBO error: check the schema before ordering a change to something you only saw in widgets_values.", "medium", "A"),
    ("NEVER hand-transcribe a pulled graph JSON from context into an archive file. A 30 KB graph is thousands of numeric node and link ids; one transposed digit produces an archive that silently LIES to every future session. Archiving requires a direct pull-to-disk path. Prose verification records are safe; hand-copied JSON is not.", "high", "A"),
    ("The in-app agent's replies have twice arrived DEGRADED: round 8 was truncated mid-instruction (it declared a placeholder rather than guessing — correct), and rounds 8+10 came back with tab and node names flattened to the literal strings 'node' and 'fx-dub the model'. Never resolve a garbled or truncated reference by inference. Pull the graph and look.", "medium", "A"),
    ("AudioMix ADOPTS audio_1's SAMPLE RATE and the LONGER duration. MEASURED 2026-08-22: VO(24k) as audio_1 + bed(48k) as audio_2 -> 24 kHz mix (the 48 kHz bed is DOWNSAMPLED, losing everything above 12 kHz); bed(48k) as audio_1 + VO(24k) as audio_2 -> 48 kHz mix. There is NO sample-rate-conversion node anywhere on cloud (re-verified: only 'Sigmas Resample' for diffusion schedules and 'Load Lynx Resampler', a model loader), so INPUT ORDER IS THE ONLY LEVER. Put the highest-rate source on audio_1. AudioMerge also yields 48 kHz.", 'high', "A"),
    ("Florence2Run's caption output is a LIST when fed an IMAGE BATCH, and SaveText cannot write a list: TypeError write() argument must be str, not list. VHS_SelectEveryNthImage(30) on 161 frames yields 6 images -> 6 captions -> the whole job dies at the SaveText node. Static validation CANNOT catch this (the socket type is STRING either way). Fix: feed Florence exactly one image (select_every_nth >= frame count, or ImageFromBatch), or join with 'Basic data handling: StringDataListJoin'. MEASURED: killed both the v2.2 and turbo audition runs.", 'high', "A"),
    ("ACE-Step 1.5 IS A MUSIC MODEL AND IS THE WRONG TOOL FOR AMBIENCE/SFX. The Director's verdict on the first audition: 'I didn't hear any sfx.' The purpose-built cloud paths are ElevenLabsTextToSoundEffects (eleven_sfx_v2 -- MEASURED 48 kHz stereo, EXACT requested duration, a loop flag for seamless beds, prompt_influence 0-1) and the stable_audio_3_*_sfx checkpoints. Reserve ACE-Step for music cues.", 'high', "A"),
    ('EVERY text-to-speech option on cloud decodes 24 kHz MONO -- measured across FL_ChatterboxTTS, FB_Qwen3TTSVoiceDesign and FB_Qwen3TTSCustomVoice. So the dialogue can never be the highest-rate source; the ambience bed must always take the audio_1 slot to hold the mix at 48 kHz.', 'high', "A"),
    ("VOICE DIRECTION ON CLOUD DOES NOT NEED CLONING. FB_Qwen3TTSVoiceDesign takes a free-text instruct field describing the voice ('world-weary man in his fifties, low gravelly voice, film-noir delivery') and synthesises to it; FB_Qwen3TTSCustomVoice exposes 9 named presets (Aiden/Dylan/Eric/Ono_anna/Ryan/Serena/Sohee/Uncle_fu/Vivian) PLUS its own optional instruct. Both are local models (no API charge). This supersedes the standing 'voice cloning is local-only' constraint for the DIRECTION use case -- cloning a specific real voice still needs reference AUDIO and stays local.", 'high', "A"),
    ('EBU R128 INTEGRATED loudness GATES OUT a quiet bed, so mix_lufs minus vo_lufs CANNOT measure ducking depth. MEASURED: VO -16.22 LUFS, bed after -15 dB gain -39.29 LUFS, mix -16.22 LUFS -- byte-identical to the VO reading (they content-address to the same asset). The bed sits ~13 dB below the relative gate and is excluded from the integrated figure entirely. To verify a dialogue-to-bed offset you must METER THE BED STEM DIRECTLY; the graph needs a third AudioLoudnessMeter.', 'high', "A"),
    ("The -15 dB bed gain is ABSOLUTE, not relative, and ACE-Step already generates ~8 dB below the dialogue -- so the delivered separation was 23 LU, not the 15 the dispatch specified, and the Director could not hear the bed at all. Measure the bed's own LUFS and set gain from the MEASURED delta, never from a fixed number.", 'high', "A"),
    ('A job that fails at ANY node loses EVERY output -- ComfyUI does not persist the outputs of nodes that completed before the error, and the failed job posts no billed gpu_seconds. Isolate risky or unproven nodes into their own job rather than adding them to a graph whose other outputs you need.', 'medium', "A"),
    ('When rebuilding a signed GCS output URL by hand, response-content-disposition IS PART OF THE SIGNATURE. Dropping it returns SignatureDoesNotMatch and curl writes the 869-byte XML error body into your .flac. Carry the full query string from get_output verbatim, and check file sizes after download.', 'medium', "A"),
    ('submit_workflow accepts hand-authored API-format JSON and dry_run:true validates it for free (node existence, link integrity, required inputs) -- so an advisor session can build and run probe graphs DIRECTLY, with no in-app-agent round trip. This is the fastest path to settling a measurement question. Editor/save format is rejected; that path is save_workflow + run_saved_workflow.', 'high', "A"),
    ("run_saved_workflow's input_overrides ({nodeId:{inputName:value}}) changes widget values at submit time WITHOUT editing the saved graph -- ideal for testing a hypothesis against the real audition graph. Used 2026-08-22 to force VHS_SelectEveryNthImage to 161 (one frame to Florence), which confirmed the caption-list diagnosis and produced the first successful fx-dub run.", 'medium', "A"),
    ("LoadAudio RESOLVES A CLOUD STORAGE KEY THAT ITS COMBO DOES NOT LIST -- exactly like LoadVideo. MEASURED 2026-08-22: LoadAudio.audio COMBO enumerates [] (empty), yet feeding it a SaveAudioAdvanced output's storage key round-trips the file EXACTLY (reloaded bed metered -17.20 LUFS, identical to the original). CONSEQUENCES: (1) re-mixing is free, deterministic and needs no regeneration -- pull stem storage keys from get_output and rebuild the mix; (2) the standing 'cloud has NO audio-upload path, so voice cloning is local-only' constraint is BROKEN OPEN -- a reference clip that reaches the asset store can feed FL_ChatterboxTTS.audio_prompt or FB_Qwen3TTSVoiceClonePrompt by storage key.", 'high', "A"),
    ("GAIN-STAGE FROM MEASURED STEM LOUDNESS, NEVER FROM A FIXED dB NUMBER. The two TTS engines differ by 8 dB on the same line (Chatterbox -16.22 LUFS, Qwen3 VoiceDesign -23.94), so any hardcoded bed gain is wrong for one of them. The working recipe, measured 2026-08-22: meter both stems, boost the VO with AudioAdjustVolume (INT dB), then set the bed's mix gain so VO-minus-bed lands in the 8-20 LU ducking band. For v2.3: VO +10 dB -> -13.94 LUFS, bed -9 dB -> -26.20, separation 12.26 LU, mix -18.05 LUFS against an -18.0 target.", 'high', "A"),
    ("ImageFromBatch(batch_index=80, length=1) is the RIGHT caption fix, not merely a bug workaround -- it also picks a better frame. Frame 0 of the audition clip captions as 'a person standing in a dark room'; mid-clip frame 80 captions as 'two men standing in a city at night, facing each other', which actually matches the dialogue scene. Sample the MIDDLE of a shot, not its first frame.", 'medium', "A"),
    ("ElevenLabs eleven_sfx_v2 takes POSITIVE claims only. Asking for footsteps 'splashing through shallow puddles on wet concrete' produced puddle-splashing the Director rejected; 'hard leather heels striking damp solid stone, dry impact on a wet hard surface' produced the wanted sound. Do NOT write 'no splashing' -- negation collapses to 0.2-1.1 percent accuracy in audio-text models (arXiv:2607.12290, our own study-swarm finding 15). Exclude by positive description instead.", 'high', "A"),
    ("DEFAULTING TO THE FREE LOCAL MODEL IS A COST-OPTIMISATION AND THE DIRECTOR HAS FORBIDDEN IT. After being told explicitly to stop budgeting, I still reached first for the free local TTS (Qwen3/Chatterbox) and then papered over the resulting length problem with a post-hoc AudioSpeedShift, instead of going straight to ElevenLabs and using its own speed control. Verdict: 'Why are you using cheap techniques when I said that I have credits to burn?' Reach for the premium engine FIRST; use its native controls rather than post-processing. See [[feedback-stop-budgeting-credits]].", 'high', "A"),
    ("A PRESET VOICE LIST IS NOT A CHARACTER VOICE. Five engines and 30+ preset voices later the Director's verdict was still 'none of these sound very natural, and only Brian is anywhere near deep enough.' Shopping a preset roster is the wrong shape of solution for a specific character; VOICE CLONING from a supplied reference is. This became actionable the moment LoadAudio was proven to resolve storage keys, because reference audio can now reach ElevenLabsInstantVoiceClone / FishAudioInstantVoiceClone.", 'high', "A"),
    ('ElevenLabsTextToSpeech is the quality tier: eleven_v3 or eleven_multilingual_v2, a NATIVE model.speed control (0.7-1.3) that removes any need for time-stretching, stability / style / similarity_boost, and opus_48000_192 output. MEASURED 2026-08-22: 48 kHz stereo, and the four-line scene came in at 8.880 s (Roger+Brian) versus 11.494 s from the local engine - i.e. the premium path solved the fit problem for free, without the AudioSpeedShift hack.', 'high', "A"),
    ("A CHECK THAT PUNISHES AN UPGRADE IS A BROKEN CHECK. audition_receipt's stem_vo rate check hardcoded 'all cloud TTS is 24 kHz' - true of the local engines - and therefore went RED when ElevenLabs delivered 48 kHz, which is strictly better. Fixed to accept the runtime rate OR a TTS-native rate. When a measured constant becomes a gate, re-derive it the moment the platform surface changes.", 'medium', "A"),
    # --- session 4 (2026-08-22): the voice-resolution cycle -------------------
    ("ElevenLabsInstantVoiceClone.files is an auto-grow list whose RUNTIME slot name is files.audio0, NOT the files.item_1 that get_node advertises. dry_run PASSES the wrong name (pre-flight only checks that link targets resolve), so the defect is invisible until the job fails at execution. Detector: graph_lint.api_autogrow_slot_name.", "high", "A"),
    ("A dry_run PASS is not proof the runtime accepts a graph. Pre-flight validates node existence, link integrity and required-input presence against a bundled catalog; it does not validate dotted auto-grow/dynamic-combo slot NAMES. Two shapes passed dry_run and then failed at execution (files.item_1, model.voices.item_1).", "high", "A"),
    ("COMFY_AUTOGROW_V3 is a container declaration, not a wire type. Searching for 'what node outputs COMFY_AUTOGROW_V3' returns zero producers and invites the false conclusion that the input cannot be fed at all; the slots it grows accept ordinary AUDIO links. The in-app agent reached exactly that false 'definitive no' on 2026-08-22 and recommended abandoning voice cloning; one job refuted it (920dc2e0-e420-473a-9cb9-45b84b0fea65).", "high", "A"),
    ("FishAudioTextToSpeech rejects model.voices.item_1 at execution ('unexpected keyword argument') even though get_node lists it with auto_grow_slots. The s1 model's single model.voice input works. Fish Audio IS on the platform (4 nodes under partner/audio) contrary to an agent report that it is absent.", "medium", "A"),
    ("AudioPad (ComfyUI_AudioTools) is BROKEN on Comfy Cloud: every call raises UnboundLocalError: cannot access local variable 'pad_samples'. Place a clip on a timeline with EmptyAudio + AudioConcat instead. Isolating it in its own job is what saved the paid render in the same wave.", "medium", "A"),
    ("ByteDanceSeedAudio pitch_rate is a NODE-level knob: it shifts every speaker in the prompt by the same interval, so one node cannot carry two differently-pitched characters. Render one pass per character and layer them - the timestamps are an ABSOLUTE output timeline (a line at [2.3s:4.0s] renders 4.032s with the leading silence written in), so passes mix without alignment work.", "high", "A"),
    ("ByteDanceSeedAudio in reference_mode='audio reference' reproduces the reference clip's DIALOGUE CONTENT, not just its timbre. A four-line reference made it re-speak a line the prompt omitted; mixed against the real take it read as two men talking over each other. References must be one speaker, and every audio-reference render must be gated by tools/dialogue_receipt.py --only-speaker.", "high", "A"),
    ("Cross-engine voice cloning does not preserve identity: a ByteDance voice cloned into ElevenLabsInstantVoiceClone came back approximated and was rejected by ear. ElevenLabs' own guidance wants real speech; 9.8s of pitch-shifted synthetic audio is a weak reference. Same-engine reference (ByteDance audio-reference) held where cross-engine did not.", "high", "A"),
    ("ByteDance text-only voice design is non-deterministic REGARDLESS of seed (its own spec says so), so a voice approved in one render cannot be recalled in the next. Treat text-only as CASTING; once a take is approved, every later line must come from that take by reference or by verbatim lift. Re-rolling an approved character is the single fastest way to waste the Director's time.", "high", "A"),
    ("eleven_v3 inline audio tags DO work on this platform (measured, not quoted): '[gruff] Not bad. [tired] Can't complain.' transcribes as 'Not bad. Can't complain' - the tags are consumed as delivery directives, not spoken - and the take runs 2.880s against 2.240s for the identical voice/seed/settings without them. This closes the round-11 open question.", "medium", "A"),
    ("Container metrics cannot see content defects. Sample rate, duration and LUFS all passed green on two VO stems the Director rejected within seconds (a phantom extra line; a mid-line pause that ran into the next cue). Gate VO with tools/dialogue_receipt.py, which checks the spoken content against docs/scenes/*.json via a diarized transcript.", "high", "A"),
    ("ElevenLabsSpeechToText rejects num_speakers together with diarize (set num_speakers=0), and caps model.diarization_threshold at 0.4 (default 0.22). With those set it returns word-level speaker-tagged timings - the cheapest way to locate one character's line inside a mixed stem for a verbatim lift.", "low", "A"),
    ("The full partner/audio surface is 16 nodes across 5 engines: ElevenLabs (selector 21 presets / TTS / TextToDialogue multi-speaker / SpeechToSpeech / InstantVoiceClone / SFX / STT / isolation), Fish Audio (selector 17 presets + custom voice_id / TTS / clone / STT), ByteDance Seed Audio (40 presets, 4 reference modes, 8k-48k, pitch +/-12 semitones), HeyGen (67 voices, SSML, 44.1kHz MONO), Sonilo (music). ElevenLabsTextToDialogue and ElevenLabsSpeechToSpeech were never surveyed before session 4.", "low", "A"),
    # --- opened by session 5 (lip-sync in post, rounds 12-15) ---
    ('A relay that flattens node class names also flattens them in the message DENYING it. The round-12 reply, written to state the agent had not sent `node` placeholders, arrived carrying three of them plus one flattened to empty. With rounds 8, 10, 12-inbound, 13 and 14 that is seven occurrences. CONSEQUENCE: neither party transcript of the other is authoritative for NAMES. Class names, storage keys and job ids must be re-derived from the live catalog or get_output at the point of use, never transcribed across the Director relay.', 'high', 'A'),
    ('Do NOT demand execution-proof as a PRECONDITION of the execution that produces it. Round 12 asked the agent for runtime-proven slot names and an execution-proven VIDEO route before the only run that could establish either, while forbidding dry_run as an answer - three circular asks in one brief. Separate preconditions from outputs when briefing an agent whose only proof mechanism is a completed job.', 'high', 'A'),
    ('Do NOT assign a capability to a counterparty without establishing it HAS that capability. Round 12 called reading face coordinates off a decoded frame "genuinely yours" to a text-only agent with no visual grounding. Round 15 then called the frame extract "within your surface" while conflating two different mechanisms - a 4-node canvas build (needs a focused tab) and its ffmpeg frame-grab path (needs a library id). Establish the mechanism, not just the task.', 'medium', 'A'),
    ('A per-character STEM and a per-character POSITIONED TRACK are different artifacts. dialogue_receipt --only-speaker consumes the second (the line at its scene position against the full timeline, silence elsewhere); saying "stem" sends a builder to the first. MEASURED: MAC speaks 2.279-3.959s, his isolated content is 1.72s, and his ByteDance render is 4.032s - the 2.312s difference IS the leading silence, confirming the absolute-timeline behaviour and making the render already positioned.', 'high', 'A'),
    ('get_output takes a prompt_id. Handed a storage hash it returns HTTP 400. There are THREE addresses for one artifact, not two: the job prompt_id, the cloud storage key, and the sha256 of the bytes - and a stored asset own metadata needs the library id, a fourth. Round 13 told the agent to call get_output on two storage keys: a type mismatch, not a refusal.', 'medium', 'A'),
    ('A partner node operating constraints can live ONLY in its description string, where the validator cannot see them. KlingLipSyncAudioToVideoNode states 720-1920px and 2-10s in prose and exposes NO height/width/length widgets, so a violating graph validates clean and fails SERVER-SIDE after credits commit. Sibling of the dry_run-is-not-proof rule: read the description text as part of the contract, not as documentation.', 'high', 'A'),
    ('A NODE SCHEMA CAN DIFFER BETWEEN TWO TOOL SURFACES READING THE SAME LIVE CATALOG. MEASURED 2026-08-23: our get_node AND search_nodes(detail=full) both return SyncLipSyncNode with nine required entries and a full input_details block carrying five conditional model.* sub-fields; the in-app agent surface returns FOUR and carries no input_details structure AT ALL - for ANY node, confirmed by the agent as a general property of its tooling, not a dynamic-combo special case. Round 11 taught advertised != runtime; this teaches ADVERTISED != ADVERTISED. Before concluding a node lacks an input, read it from a second independent surface. Every schema claim in this thread about conditional or dynamic sub-fields is structurally incomplete on the agent side and must be re-read our side.', 'high', 'A'),
    ('SyncLipSyncNode.model.speaker_selection DEFAULTS to "default" (let the model decide). Building the node without setting it produces a completed, green, plausible run that picks a face on its own, mouths the line on whichever person it chose, returns a valid MP4 and PASSES EVERY CONTAINER CHECK - no error, no failed validation, wrong content. This is the container-metrics-cannot-see-content trap landing in the VISUAL domain, where fx-dub has no receipt yet. Caught before a paid run by the agent refusing to build past a gap in its own surface.', 'high', 'A'),
    ('SyncLipSyncNode.model.sync_mode sets the OUTPUT LENGTH, so it is a deliverable-integrity knob, not a convenience: bounce/loop/remap all return audio length (remap time-stretches the picture), cut_off returns the shorter track, and only "silence" pads the shorter one and preserves the source frame count. For a 10.0625s / 161-frame picture against a shorter VO, silence is the ONLY mode that survives the existing frames-intact check. Its seed tooltip also states results are non-deterministic REGARDLESS of seed - the cast-once/lock-the-take rule now applies to the picture.', 'high', 'A'),
    # --- measured by session 5's lip-sync run (rounds 16-17) ---
    ('SyncLipSyncNode RE-TIMES THE PICTURE. MEASURED 2026-08-23: a 161-frame / 16.000 fps / 10.0625s source returned 473 frames at ~47 fps over the SAME 10.0625s, and the 1.4375s probe returned 68 frames from the same source. Duration and resolution are preserved exactly (832x480); FRAME COUNT IS NOT. Any receipt asserting "161 frames intact" on a lip-synced deliverable fails on every sync.so output regardless of correctness - verify duration, resolution and audio-track survival, and treat frame count as re-derived.', 'high', 'A'),
    ('ImageFromBatch CLAMPS AN OUT-OF-RANGE batch_index SILENTLY - it returns the LAST frame instead of erroring. MEASURED twice: indices 34 and 58 of a 23-frame decode, and 160 and 300 of a 161-frame decode, each returned byte-identical content hashes. Compounding it, GetVideoComponents decodes at the SOURCE frame rate (161 frames at 16 fps) even when the container carries 473 frames at 47 fps. Anyone reading a NAMED frame out of a batch can silently receive a different frame with no error - fatal when the frame index is load-bearing (e.g. reading face coordinates for speaker_frame). Cross-check by content hash before trusting an index.', 'high', 'A'),
    ('SaveVideo.codec.encoding CRASHES LOCAL PRE-FLIGHT: sending "codec.encoding": "auto" returns "candidate.toLowerCase is not a function" and NO verdict. Its options are OBJECTS ({"key":"auto","inputs":{...}}), not strings, and the validator lowercases them. Omitting the field validates clean. The hazard is second-level dotted fields whose options are objects rather than strings.', 'medium', 'A'),
    ('THE ROUND-11 ADVERTISED-IS-NOT-RUNTIME TRAP IS NOT UNIVERSAL. MEASURED 2026-08-23: all five dotted SyncLipSyncNode model.* fields (sync_mode, speaker_selection, speaker_frame, speaker_x, speaker_y) were accepted by the runtime EXACTLY as get_node advertised them - no files.item_1 -> files.audio0 divergence. Advertised names must still never be ASSUMED accepted, but a divergence is a per-node fact, not a property of COMFY_DYNAMICCOMBO_V3.', 'medium', 'A'),
    ('REMOVE A PADDING-DIRECTION QUESTION RATHER THAN ANSWERING IT. sync_mode "silence" pads the shorter track but the schema never says WHERE - head or tail - and the only test costs a full-duration paid run. Building the driving track to EXACTLY the picture duration (EmptyAudio lead + clip + EmptyAudio tail, measured to 483000 samples / 48 kHz = 10.0625s, delta 0.0000s) leaves nothing to pad and makes the question moot for free. Prefer eliminating an unknown over buying the answer.', 'high', 'A'),
    ('THE CLOUD KEY AND THE LOCAL FILE ARE NOT THE SAME ARTIFACT JUST BECAUSE THEY DESCRIBE THE SAME TAKE. Round 14 asserted MAC\'s ByteDance render "already carries the leading silence" from a LOCAL 4.032s file and told the agent to use cloud key d7ba748c... directly; that key decodes to 1.415s of speech with NO leading silence. Under sync_mode silence the pad lands at the tail, so the mouth would have moved at 0.0-1.415s instead of 2.279-3.694s - a green, correctly-framed, well-synced run with the line in the wrong place. Measure the CLOUD artifact before instructing anyone to use it.', 'high', 'A'),
    ('FLORENCE-2 HALLUCINATED A SECOND PERSON INTO THE CAPTION THAT DRIVES THE AUDIO PROMPT. The delivered run\'s caption_00001.txt reads "two men standing in a city at night, facing each other." MEASURED from decoded frames 20/60/120: there is ONE man on screen for the whole clip, facing camera - the Director confirmed the second man is off camera the entire time. That caption is the semantic intermediate feeding the ambience prompt and NOTHING in the pipeline checks it against the picture. Two downstream claims of ours died with it (the "two men facing each other" framing and the "profile faces at 480p" risk).', 'high', 'A'),
    # --- measured by session 5's re-mux round (2026-08-23) ---
    ('AudioVideoCombine IS BROKEN ON COMFY CLOUD: every call raises "ImportError: TorchCodec is required for save_with_torchcodec". It is the obvious node for laying an audio track over a VIDEO and it cannot run. Mux via GetVideoComponents -> VHS_VideoCombine(images, audio) instead, with frame_rate driven by the LINK from GetVideoComponents slot 2. Second entry in the broken-on-cloud registry after AudioPad; both are now in graph_lint.BROKEN_ON_CLOUD.', 'high', 'A'),
    ('AudioMix GAINS ARE CLAMPED TO -24..+6 dB. Submitting gain_2_db=7.0 returns value_bigger_than_max. The delivered mix recorded as "VO +7 dB, bed gain_1_db -12" therefore CANNOT have come from AudioMix alone - the VO boost is an AudioAdjustVolume node (core, volume in dB, INT) ahead of the bus. Reproduced and confirmed byte-identical. A recipe that names a gain without naming the node that applies it is not reproducible.', 'high', 'A'),
    ('THE LIP-SYNC RE-TIMING IS INTERMEDIATE, NOT DELIVERED. SyncLipSyncNode returns 473 frames at ~47 fps from a 161-frame / 16 fps source, but GetVideoComponents decodes at the SOURCE cadence, so the mux round-trip (GetVideoComponents -> VHS_VideoCombine) hands back 161 frames at 10.0625s. MEASURED on the final artifact: 832x480, 161 frames, video 10.0625s, audio 10.0693s, both tracks present - the original contract intact. Assert frame-count preservation on the DELIVERABLE, never on the raw sync output.', 'high', 'A'),
    ('A CLOUD MIX REBUILT FROM STEM STORAGE KEYS IS BYTE-IDENTICAL TO THE ORIGINAL. MEASURED 2026-08-23: the v28 mix rebuilt from bed d8ef106a + VO 8eadf234 through AudioAdjustVolume(+7) -> AudioMix(gain_1_db=-12) has FLAC STREAMINFO md5 c34976a8594c3705cc3622eef75033f6, matching the delivered mix exactly. The FLAC md5 in STREAMINFO (bytes 18-34 of the block body) is a free, exact equality test on decoded audio and needs no decoder - use it to prove a rebuild rather than trusting a duration match.', 'high', 'A'),
    ('RETRACTED 2026-08-23 (was: "the delivered MAC artifact is neither key the handoff names"). THE HANDOFF WAS RIGHT AND WE WERE WRONG. Proven by byte-identity: AudioMix(b7066f85..., place(d7ba748c..., 2.30s)) reproduces the assembled VO 8eadf234... EXACTLY (FLAC STREAMINFO md5 e65dc81785b6d97bf043d6717f63710f), and that VO at +7 dB reproduces the delivered stem_vo (b2816092...), which mixed with the bed at -12 dB reproduces the delivered mix (c34976a8...). There is no third key. THE ERROR: we read diarized word timings (MAC 2.279-3.959s, so ~1.68s) as a MEASUREMENT of the audio\'s extent and used it to contradict a byte-level fact. They are a transcription model\'s boundary estimates - here 0.021s early at the start and 0.244s late at the end against a clip that truly spans 2.30-3.715s. A model\'s output is evidence, not a probe. We wrote the contradiction into HANDOFF, a relayed brief, the CHANGELOG and this DB before testing it, while documenting the caption hallucination - the same class of error.', 'high', 'A'),
    # --- provenance retraction, 2026-08-23 ---
    ('THE WHOLE DELIVERED RUN IS REPRODUCIBLE FROM THREE STORAGE KEYS, proven byte-identical 2026-08-23 by FLAC STREAMINFO md5 at every hop: VOICE b7066f85... + MAC d7ba748c... placed at 2.30s -> assembled VO 8eadf234... (e65dc817...); that VO through AudioAdjustVolume(+7) -> the delivered stem_vo (b2816092...); that plus bed d8ef106a... through AudioMix(gain_1_db=-12) -> the delivered mix (c34976a8...). Re-mixing is free and exact. The FLAC md5 lives in STREAMINFO bytes 18-34 of the block body and needs no decoder, so equality is testable locally at zero cost.', 'high', 'A'),
    ('THE DELIVERED stem_vo IS POST-GAIN WHILE THE BED STEM IS PRE-GAIN. MEASURED 2026-08-23: the run\'s stem_vo is byte-identical to the assembled VO with +7 dB already applied, but the bed stem ships at its pre-gain level and the mix applies -12 dB on the bus. That asymmetry is exactly why audition_receipt needs --bed-gain-db and why its default of -9 reports the ducking depth 3 LU low on this run. The deliverables are NOT all at the same stage of the gain chain; do not assume a "stem" means pre-gain.', 'high', 'A'),
    ('DIARIZED WORD TIMINGS ARE A MODEL\'S ESTIMATES, NOT A MEASUREMENT OF THE FILE. MEASURED 2026-08-23: MAC\'s clip truly spans 2.300-3.715s, and the diarizer reported his words at 2.279-3.959s - 0.021s early at the head and 0.244s late at the tail. We used that ~1.68s span to "prove" a 1.415s artifact could not be the shipped one, and published the wrong conclusion. Word timings are correct enough to gate CONTENT (order, overlap, gaps) and too loose to establish an artifact\'s EXTENT. For extent, decode the file.', 'high', 'A'),
    # --- CI trigger duplication, measured 2026-09-14 ---
    ('A CONCURRENCY GROUP CANNOT COLLAPSE A push/pull_request DOUBLE-FIRE IF IT IS KEYED ON "github.head_ref || github.ref". MEASURED 2026-09-14: commit 5051536 applied exactly that form to ci.yml as the fix, and two FULL matrices still completed on one SHA (77cc70f - runs 34904826500 push, 34904846190 pull_request). head_ref is EMPTY on a push, so the groups resolve to "ci-refs/heads/<branch>" and "ci-<branch>" - different strings, no cancellation. A form that does share a group is "github.event.pull_request.head.ref || github.ref_name" (ref_name is already the short name on a push). The fix MEASURED here is the trigger filter, not the group.', 'medium', 'A'),
    ('AN "on.push" WITH NO "branches" FILTER ALSO FIRES ON TAG PUSHES, so every release ran ci TWICE on the same commit. MEASURED 2026-09-14 by grouping the ci run history by head SHA: 5 duplicate-SHA pairs, and 4 of them are main+tag (ddd6e671 v1.1.1, b4029ac0 v1.1.0, 9fb75f3c v1.0.0, 2cbeac74 v1.0.1). Concurrency can NEVER fix this class - the tag push happens minutes after the main push, so there is nothing in-progress to cancel. Only a trigger filter removes it. Detector: tests/test_workflows.py double_fire_problems(), proven red against the real pre-fix ci.yml and green against the fixed one.', 'medium', 'A'),
    ('A DUPLICATE CI RUN IS INVISIBLE IN THE UI - it renders as two green checks and nobody counts them. Both fx-dub duplicate classes survived a dedicated "collapse the double-fire" commit because the verification read the YAML instead of grouping completed runs by SHA. The probe that finds it: gh run list --workflow=ci.yml --json event,headBranch,headSha | group_by(.headSha) | map(select(length>1)). Do not accept a CI trigger change on the strength of the config diff.', 'medium', 'A'),
]

DECISIONS = [
    # (id, choice, findings)
    ("A", "Caption-mediated pipeline by design; v1 targets ambience/dialogue-grade sync and says so. Timing never comes from richer captions.", "dispatch findings 1-3, 13"),
    ("B", "Three-layer output (bed / spots / dialogue) mixed from stems, never a single generated mix.", "7, 38, 44"),
    ("C", "Bed <= 60 s single window; longer videos segment at shot boundaries with overlap+crossfade; min segment 2 s.", "4, 5, 6 + prompt-lab 60 s ceiling"),
    ("D", "Deterministic SUBTRACTIVE caption->audio-prompt rewrite stage (temperature 0, pinned, cached). Host-side Ollama or manual box on cloud.", "9-12, 14-17"),
    ("E", "Dialogue is human-authored, never generated from the caption.", "21 + house rule"),
    ("F", "Mix: 48 kHz bus target, dialogue anchor, bed -15 LU (ambience) / -10 LU (music), integrated -18 LUFS, TP -1 dBTP; offsets exposed; manifest reports BS.1770 rev, gated+ungated LUFS, TP, LRA, SBLD<4LU windows.", "28-36"),
    ("G", "Governance as feature: consent-gated local-only cloning, Perth stays on, manifest = Art.50 machine-readable mark, no person-specific voice packs, no robocalls.", "19-27"),
    ("H", "Dub kit deliverables: dubbed.mp4 + mix.flac + stems/ + caption.txt + audio_prompt.txt + manifest.json.", "37-44"),
    ("I", "Model lanes: MIT default (ACE 1.5 + Chatterbox + Florence-2); SA3 conditional lane; direct-V2A non-commercial lane; Qwen3-TTS Apache cloud VO alt.", "KB license wall"),
    ("J", "External verification at every layer: graphs validation-green, audio verified by meters, citations by different-family verifier, agent claims re-verified over the API before acting.", "protocol"),
]

NEXT_ACTIONS = [
    ('SHIPPED 2026-08-23: fx-dub v1.1.0 published to PyPI via Trusted Publishing (OIDC, release workflow run 32635638295). Published wheel verified from the index: __version__ 1.1.0, --scene supported, caption check present, all six picture builders exported. CI green on main and on the tag; GitHub Pages redeployed and the new handbook sections are live. All seven translations regenerated on TranslateGemma 27B BEFORE the tag, so the release commit carries source and translations in step.', 'advisor session', 'done'),
    ("RESOLVED 2026-08-22: no upload was ever needed. The clip is already reachable as cloud asset ea68c5aa....mp4, byte-identical to the local fixture (confirmed via get_output + local probe). fx-dub v2.2's loader is CLEARED.", "Director", "done"),
    ("RESOLVED 2026-08-22: the PrimitiveFloat 16.0 -> VHS_VideoCombine.frame_rate link is VERIFIED present on input slot 4 of fx-dub v2.2 (link 718920623009028; api_format resolves to the link, not a literal). The round-6 deferred check is closed.", "advisor session", "done"),
    ("DONE 2026-08-22: round-10 brief relayed; turbo tab rebuilt and verified value-by-value against v2.2 — exactly three values differ (unet_name / steps 8 / cfg 1), matching the official template. Both graphs cleared to run.", "Director + advisor", "done"),
    ("SUPERSEDED 2026-08-22 (session 4): the v2.2-vs-v2.1-turbo A/B measured the ACE-Step ambience path, and ACE-Step is RETIRED from that path - it is a music model whose rain bed metered -39.29 LUFS and was inaudible to the Director. ElevenLabs eleven_sfx_v2 is the SFX/ambience engine. Do not chase this A/B; it measures a path we no longer use.", "Director", "done"),
    ("SUPERSEDED 2026-08-22 (session 4): archiving the v2.2 / v2.1-turbo tabs preserved the retired ACE-Step ambience path. The live pipeline is built by tools/vo_graphs.py, whose builders ARE the durable form and are covered by graph_lint.API_DETECTORS + tests. The graph_lint forward gate stays pointed at the archived v2.1. If a future session wants those tabs on disk, pull them - do NOT hand-transcribe (see the transcription trap).", "advisor session", "done"),
    ("Add a graph_lint detector for the mux frame_rate trap: VHS_VideoCombine.frame_rate must be LINK-driven, never a bare widget (the widget beneath the live link reads 8; cutting the link silently yields a 20.1 s dub). Note the control_after_generate detector idea is DROPPED — Florence2Run has no such schema input, so there is nothing to lint.", "advisor session", "open"),
    ("DONE 2026-08-22: the audition RAN. Receipt 14/18 committed at runs/2026-08-22-audition-01/receipt.json. The dubbed MP4 carries audio with 161 frames intact. Mix-bus sample rate SETTLED (AudioMix takes audio_1's rate).", 'advisor session', 'done'),
    ("DONE 2026-08-22: fx-dub v2.3 built and verified 19/19. Director picked V1 (Qwen3 VoiceDesign gritty) and the layered ElevenLabs bed; footsteps corrected to wet concrete after his FAIL on the puddle take.", "advisor session", "done"),
    ("DONE 2026-08-22: Director chose footsteps take A (leather heels on wet concrete). Bed is locked: ElevenLabs eleven_sfx_v2 rain + footsteps-A at -4 dB, storage key d8ef106aaa16af33f449e3097f9d4fe78b42a767e508b0476dd7777e20ddfff3.flac, -17.20 LUFS, 48 kHz.", "Director", "done"),
    ("RESOLVED 2026-08-22 (session 4): the dub is DELIVERED. runs/2026-08-22-v28-bytedance scores 19/19 and the VO scores 11/11 on the new dialogue_receipt. VOICE = ByteDance cast take re-spoken via same-engine audio reference (seed 502); MAC = ByteDance acoustic grit brief, spliced to close a 1.880s pause. Both approved by ear. The round-11 brief was overtaken by direct probing - its Item 4 answer (that cloning is impossible) is WRONG and refuted by job 920dc2e0-e420-473a-9cb9-45b84b0fea65.", "Director + advisor", "done"),
    ("DONE 2026-08-22: voice cloning CONFIRMED working on cloud - LoadAudio storage key -> FB_Qwen3TTSVoiceClonePrompt -> RoleBank -> DialogueInference produced a real two-role exchange. The remaining question, in the round-11 brief, is whether the same LoadAudio path feeds the PREMIUM clone nodes (ElevenLabsInstantVoiceClone / FishAudioInstantVoiceClone).", "advisor session", "done"),    ("DONE 2026-08-22: audition_receipt.py corrected. dialogue_anchored now computes VO-minus-BED from two stem meters (a bed_lufs manifest is REQUIRED; absent it the verdict is an honest FAIL, never a pass by omission). Source stems check native_rate instead of rate48k, and rates_agree considers only delivered masters. 102 tests green; the falsifiability gate forced red cases for every new check.", "advisor session", "done"),
    ('Fold into the next readouts model-knowledge wave: AudioMix rate/duration reconciliation, the ElevenLabs SFX measurements (48 kHz, exact duration, loop flag), Qwen3-TTS VoiceDesign as the cloud voice-direction path, and all-cloud-TTS-is-24-kHz-mono.', 'advisor session', 'open'),
    ("SUPERSEDED 2026-08-22 by the v2.2+turbo audition action above (v2.1 is no longer the audition graph). The post-run measurements it named still stand and are carried by tools/audition_receipt.py: decode the mix FLAC header (SETTLES the mix-bus sample-rate question), read both LUFS manifests, and confirm the dub carries an audio track.", "Director + advisor", "done"),
    ("Fold ChatterBox/ACE-1.0 measurements into the next readouts model-knowledge wave", "advisor session", "open"),
    ("Gate the prompt-craft audio-domain dispatch's citations through roleos verify-citations -> prism BEFORE any finding becomes canon (its own standards table scores EXTERNAL_VERIFIER 1 for this reason)", "next session", "open"),
    ("Build prompt-craft `domains/audio` per docs/design/2026-08-21-promptcraft-audio-domain.dispatch.md (A1-A7) — additive plugin + one register call, core/ unchanged; respect the identity-subgate fences", "next session", "open"),
    ("Host-side rewrite runner (Ollama, deterministic, cached) — decision D, superseded in spirit by the prompt-craft audio plugin", "future session", "open"),
    ("Spot-effects event timeline (host-side shot/onset detection -> AudioPad placements)", "future session", "open"),
    ("Local-lane graphs (5090) mirroring the cloud stack", "future session", "open"),
    ("RESOLVED 2026-08-22: SHIPPED to PyPI as fx-dub 1.0.0 (not npm - it is a Python package). Trusted Publishing via OIDC: workflow release.yml, environment release, no long-lived token. Wheel + sdist verified, installed from the index and smoke-tested. Full treatment complete: shipcheck 100% (23 checked / 0 unchecked), landing page + 6-page Starlight handbook + /llms.txt live at mcp-tool-shop-org.github.io/fx-dub/, 8 languages, 10 GitHub topics, repo-knowledge entry with thesis + architecture + 3 relationships.", "advisor session", "done"),
    # --- opened by session 4 -------------------------------------------------
    ("Recover the clipped tail on VOICE's last line: the [6.3s:9.8s] timestamp ended the render at 9.840s so the decay on 'drop by' was never generated. Re-render that ONE line against reference 0597c19d... with the window opened to ~10.0s, splice it in, re-run both receipts. Director accepted the current take as 'good enough', so this is polish, not a blocker.", "next session", "open"),
    ("RESOLVED 2026-08-22 (v1.0.1): the round-11 reply was never archived at all - only the outbound brief was. Written now to E:/AI/readouts/model-knowledge/dialogs/comfy-agent/2026-08-22-fxdub-11-reply.md with a correction banner, paired with -11-verification.md refuting it by execution (job 920dc2e0-e420-473a-9cb9-45b84b0fea65, slot files.audio0), and both rounds added to the archive thread table. Repo copies in docs/briefs/. The docs contract now models *-reply.md as a first-class kind that may never be archived without a paired verification.", "next session", "done"),
    ("Fold into the next readouts model-knowledge wave: the full 16-node partner/audio inventory (5 engines), eleven_v3 inline audio tags PROVEN working (2.240s -> 2.880s, tags not spoken), ByteDance timestamps as an absolute output timeline, ByteDance audio-reference content bleed, AudioPad broken on cloud, and cross-engine clone identity loss.", "advisor session", "open"),
    ("Extend dialogue_receipt.py to check the assembled MIX (not just the VO stem) once a scene has music or overlapping SFX - diarization on a bed-heavy mix is unverified. Today's 11/11 was measured on the VO stem, which is the honest scope of the current tool.", "future session", "open"),
    # --- opened by session 5 (lip-sync in post, rounds 12-15) ---
    ('Record the missing job_ids in kb/build_db.py RUNS: the ByteDance MAC and VOICE renders and the v28 delivery run have no prompt_id in the DB, which is why none could be handed to the agent when it needed one for get_output. Pull them from the billing feed or get_output and seed them.', 'advisor session', 'open'),
    ("DONE 2026-08-23: probe (cut_off, ~58 cr) then the full pass (silence, ~403 cr, job 4b2339b4-804a-42aa-8198-e2bf89877803). Mouth on MAC's line, closed while VOICE speaks. Original text: Build and submit the SyncLipSyncNode audition ourselves - the in-app agent is out of that build path because its tool surface cannot address the five conditional model.* fields. Sequence: frame extract (LoadVideo -> GetVideoComponents -> ImageFromBatch -> SaveImage at batch_index 20/60/120), read MAC face coordinates our side with the rig vision tooling, DIRECTOR confirms which man is MAC, then ONE isolated paid run with sync_mode=silence, speaker_selection=coordinates, speaker_frame=60, audio = d7ba748c... and video = ea68c5aa....mp4.", 'advisor session', 'done'),
    ('Re-read from OUR surface any schema claim the in-app agent has made in this thread about conditional or dynamic-combo sub-fields. Its tooling carries no input_details for any node, so every such claim is structurally incomplete rather than wrong - it could not have seen those fields.', 'advisor session', 'open'),
    ('Build the third receipt (fxdub-sync) plus graph-lint detectors for the lip-sync path: audio must trace to a per-character positioned track and never the mix; speaker_selection must be coordinates when the scene declares more than one on-frame character; sync_mode must be silence; coordinates must fall inside the declared face region. Plus the scene-contract extension (cast entries gain on_frame and face:{frame,x,y}).', 'next session', 'open'),
    # --- measured by session 5's lip-sync run (rounds 16-17) ---
    ('RESOLVED 2026-08-23: MAC face coordinates measured and verified by crosshair overlay - speaker_frame 60, speaker_x 348, speaker_y 122 on the 832x480 source. The Director confirmed one man is off camera the entire clip, so there is no which-man ambiguity: the single on-screen face IS MAC.', 'Director + advisor', 'done'),
    ('DONE 2026-08-23 (v1.1.0): audition_receipt gained caption:person_count_matches_cast and --scene; the scene contract gained on_frame. The delivered run scores 19/20 and exits 1. Original text: Fix the caption defect: the delivered run\'s Florence caption claims "two men... facing each other" when there is one man on screen. The caption feeds the audio prompt and nothing verifies it against the picture. Decide whether fx-dub gains a caption-vs-frame check, and re-record the delivered run\'s caption as Class B.', 'next session', 'done'),
    ("RESOLVED 2026-08-23 (RETRACTED, not fixed): there was no discrepancy. d7ba748c IS the shipped MAC, proven byte-identical. Our 1.68s figure came from diarized word timings read as a measurement of extent. Original text: Reconcile the MAC take provenance: HANDOFF names d7ba748c... as the shipped MAC, but it decodes to 1.415s while the delivered mix's MAC line spans 2.279-3.959s (~1.68s) by diarized word timings. Identify which cloud artifact is actually in the delivered mix and correct the handoff table.", 'next session', 'done'),
    ("DONE 2026-08-23: runs/2026-08-23-fxdub21-remux/dubbed_lipsynced.mp4 - 832x480, 161 frames, 10.0625s video / 10.0693s audio, both tracks, mix byte-identical to v28. Original text: Re-mux the shipped mix onto the lip-synced picture: runs/2026-08-23-fxdub19-lipsync/lipsync_final.mp4 currently carries only MAC's isolated positioned track. The deliverable needs the 19/19 mix (VOICE + MAC + bed) over the synced picture, then both receipts re-run plus the new duration/resolution checks.", 'next session', 'done'),
    ('Build fxdub-sync against the MEASURED behaviour, not the planned one: verify duration, resolution and audio-track survival. Do NOT assert frame-count preservation - sync.so re-times 16 fps to ~47 fps. Frame count is re-derived output, not an invariant.', 'next session', 'open'),
    # --- measured by session 5's re-mux round (2026-08-23) ---
    ('RESOLVED 2026-08-23: the shipped mix is re-muxed onto the lip-synced picture. runs/2026-08-23-fxdub21-remux/dubbed_lipsynced.mp4 - 832x480, 161 frames, 10.0625s video / 10.0693s audio, both tracks present. The mix was rebuilt from stem storage keys and proved byte-identical to the delivered v28 mix by FLAC md5.', 'advisor session', 'done'),
    ("RESOLVED 2026-08-23: the caption defect now has a check. audition_receipt gained caption:person_count_matches_cast, which compares a captioner's person-count claim against the scene contract's on_frame cast count - zero-dependency, no vision needed. docs/scenes/night-street.json gained explicit on_frame flags plus MAC's measured face coordinates. The delivered run FAILS it: the caption claims two men, the contract declares one on frame.", 'advisor session', 'done'),
    ('RESOLVED 2026-08-23: the MAC provenance discrepancy is measured, not guessed. 37d38cda = 3.624s, d7ba748c = 1.415s, delivered MAC line = ~1.68s. Neither named key is the delivered artifact. HANDOFF must stop asserting d7ba748c shipped; the true key is unrecorded and needs the job history to recover.', 'advisor session', 'done'),
    ('WITHDRAWN 2026-08-23: no third key exists; the billing-feed search would have chased nothing. Original text: Recover the THIRD MAC key actually present in the delivered mix. Needs the ByteDance VO-assembly job id from the billing feed, then get_output on it. Until then the delivered mix is reproducible only from the assembled VO 8eadf234, not from its per-character parts.', 'next session', 'done'),
    ('DONE 2026-08-23: 19/20 with --scene --bed-gain-db -12; the one failure is the caption defect, which is the finding. PROVENANCE.md names which files were carried over from v28 and why that is sound. Original text: Re-run BOTH receipts against runs/2026-08-23-fxdub21-remux once its stems and LUFS manifests are assembled there - the deliverable currently has only the mix and the dubbed MP4, so audition_receipt would report missing deliverables rather than a real verdict.', 'next session', 'done'),
    # --- provenance retraction, 2026-08-23 ---
    ('RESOLVED 2026-08-23: there is no third MAC key. The handoff\'s provenance chain is correct and was proven byte-identical at every hop (see the reproducibility trap). The open action to "recover the third key" is withdrawn - it was chasing an artifact that never existed. The billing-feed search is unnecessary.', 'advisor session', 'done'),
    ('Correct the round-17 brief section 5.2 in the next outbound round: it told the agent the delivered MAC take "is not the one in the delivered mix". That is retracted - d7ba748c IS the shipped MAC, proven by byte-identity. The agent has already read the wrong version and logged it as our open action.', 'next session', 'open'),
]

def main():
    # Drop-and-recreate in place rather than deleting the file: on Windows an open
    # reader (a test, a DB browser) holds a lock and os.remove raises WinError 32.
    c = sqlite3.connect(DB)
    for kind, name in c.execute(
        "SELECT type, name FROM sqlite_master WHERE type IN ('view','table') AND name NOT LIKE 'sqlite_%'"
    ).fetchall():
        c.execute("DROP {0} IF EXISTS \"{1}\"".format("VIEW" if kind == "view" else "TABLE", name))
    c.commit()
    c.executescript("""
    CREATE TABLE meta(key TEXT PRIMARY KEY, value TEXT);
    CREATE TABLE nodes(name TEXT PRIMARY KEY, pack TEXT, status TEXT, class TEXT, notes TEXT);
    CREATE TABLE models(name TEXT PRIMARY KEY, loader TEXT, license TEXT, commercial TEXT, class TEXT, notes TEXT);
    CREATE TABLE runs(job_id TEXT PRIMARY KEY, date TEXT, description TEXT, gpu_sec REAL, credits_approx REAL,
                      sample_rate INTEGER, channels INTEGER, bits INTEGER, duration_s REAL, sha256 TEXT, class TEXT, source TEXT);
    CREATE TABLE graphs(name TEXT PRIMARY KEY, location TEXT, workflow_id TEXT, nodes INTEGER, status TEXT, class TEXT, notes TEXT);
    CREATE TABLE threads(round INTEGER PRIMARY KEY, direction TEXT, files TEXT, state TEXT, summary TEXT);
    CREATE TABLE traps(id INTEGER PRIMARY KEY AUTOINCREMENT, trap TEXT, severity TEXT, class TEXT);
    CREATE TABLE decisions(id TEXT PRIMARY KEY, choice TEXT, findings TEXT);
    CREATE TABLE next_actions(id INTEGER PRIMARY KEY AUTOINCREMENT, action TEXT, owner TEXT, status TEXT);
    CREATE VIRTUAL TABLE fts USING fts5(kind, name, body);
    CREATE VIEW v_open_actions AS SELECT * FROM next_actions WHERE status='open';
    CREATE VIEW v_publishable AS SELECT name, license, notes FROM models WHERE commercial='yes';
    CREATE VIEW v_measured_costs AS SELECT description, gpu_sec, credits_approx, date FROM runs ORDER BY date;
    """)
    c.executemany("INSERT INTO nodes VALUES(?,?,?,?,?)", NODES)
    c.executemany("INSERT INTO models VALUES(?,?,?,?,?,?)", MODELS)
    c.executemany("INSERT INTO runs VALUES(?,?,?,?,?,?,?,?,?,?,?,?)", RUNS)
    c.executemany("INSERT INTO graphs VALUES(?,?,?,?,?,?,?)", GRAPHS)
    c.executemany("INSERT INTO threads VALUES(?,?,?,?,?)", THREADS)
    c.executemany("INSERT INTO traps(trap,severity,class) VALUES(?,?,?)", TRAPS)
    c.executemany("INSERT INTO decisions VALUES(?,?,?)", DECISIONS)
    c.executemany("INSERT INTO next_actions(action,owner,status) VALUES(?,?,?)", NEXT_ACTIONS)
    for kind, rows, keyf, bodyf in [
        ("node", NODES, lambda r: r[0], lambda r: " ".join(str(x) for x in r[1:] if x)),
        ("model", MODELS, lambda r: r[0], lambda r: " ".join(str(x) for x in r[1:] if x)),
        ("run", RUNS, lambda r: r[0], lambda r: " ".join(str(x) for x in r[1:] if x)),
        ("graph", GRAPHS, lambda r: r[0], lambda r: " ".join(str(x) for x in r[1:] if x)),
        ("trap", TRAPS, lambda r: r[0][:60], lambda r: r[0]),
        ("decision", DECISIONS, lambda r: r[0], lambda r: r[1] + " " + r[2]),
        ("action", NEXT_ACTIONS, lambda r: r[0][:60], lambda r: " ".join(r[:2])),
    ]:
        c.executemany("INSERT INTO fts VALUES(?,?,?)", [(kind, keyf(r), bodyf(r)) for r in rows])
    c.execute("INSERT INTO meta VALUES('schema_version','1')")
    c.execute("INSERT INTO meta VALUES('built_at',?)", (datetime.date.today().isoformat(),))
    c.execute("INSERT INTO meta VALUES('rule','Rebuild by editing the seed data in build_db.py and rerunning; commit script + db together. Rows: class A=measured, B=advisory; 30-day freshness rule applies.')")
    c.commit()
    for t in ("nodes","models","runs","graphs","threads","traps","decisions","next_actions"):
        print(t, c.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0])
    c.close()
    print("wrote", DB)

if __name__ == "__main__":
    main()
